services:
  - type: web
    name: pastebin-lite
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: REDIS_HOST
        fromService:
          type: redis
          name: pastebin-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: pastebin-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: pastebin-redis
          property: password
      - key: REDIS_SSL
        value: true
      - key: TEST_MODE
        value: 1

  - type: redis
    name: pastebin-redis
    ipAllowList: []
    plan: starter
